name: streamlit-app
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - setuptools  # <--- pip 밖, conda 기본 의존성에 배치하여 시스템 경로 문제를 해결합니다.
  - pip
  - pip:
    - streamlit
    - ydata-profiling==4.6.4
    - sweetviz
    - pandas
    - numpy
    - plotly
    - google-generativeai
    - optbinning
